### PR TITLE
refactor generate_pipeline_status_str()

### PR DESCRIPTION
**Pull request by clonejo**
Change-Id: Ibf7aef4c2467f4a0834ff9c3726e5fee33004c67

### CODE REVIEW

**Review by yaoyuannnn — APPROVED** [review]
Thanks for the refactoring! Looks like the CI is now running with any issues.

**Comment by yaoyuannnn** [comment]
And just curious - your branch name (`main-bf7a`) seems to be created by gerritlab, but this is GitHub, so I wonder why was that :)

**Comment by clonejo** [comment]
> And just curious - your branch name (main-bf7a) seems to be created by gerritlab, but this is GitHub, so I wonder why was that :)

I've just been creating those branch names myself ;)
But would be nice do dogfeed though.

**Comment by clonejo** [comment]
Do you expect me to merge this? I don't have permissions to do so. So, just merge when you like.

**Comment by yaoyuannnn** [comment]
I see. The author should have the permission to the PR as well. Looks like your GitHub account was not recognized as the author of the commit, maybe because the email used in your commit is not the same as the GitHub account?

**Pull request merged**
