### PR TITLE
typos

### PR DESCRIPTION
**Pull request by clonejo**
Change-Id: I25ef383920d673027cc1ee8f5ed360736b6bff5a

### CODE REVIEW

**Comment by yaoyuannnn** [comment]
Wow.. I never imagined anyone else would contribute to this little tool I created for my own use. Thanks a lot!! :)

**Review by yaoyuannnn — APPROVED** [review]

**Comment by clonejo** [comment]
Haha, there are two more bits two come. I'll create separate PRs though (now if gerritlab supported Github ;) ).

Actually i was inspired by a recent podcast on https://graphite.dev/ and went on the lookout for Gitlab tooling.

**Comment by yaoyuannnn** [comment]
Haha, thank you!!

> (now if gerritlab supported Github ;)

Oh yeah, I'm very used to the Gerrit like commit-based reviews while the company I'm working for mostly uses GitLab and so I created this. I think the same idea can be used for GitHub too.

I know Phabricator also does the per-commit review but seems like it's getting phased out. I haven't used Graphite. Is it good? :)

**Comment by clonejo** [comment]
No idea, i have not worked with either Graphite or Gerrit yet. Though i don't think i need a full Graphite.

I want to try this small-MRs workflow at work, hopefully the reviewing time can get a bit lower that way.

How do you make sure that an MR is not merged before its parent MR? We don't have that dependend-MR paid Gitlab feature, unfortunately.

**Comment by yaoyuannnn** [comment]
> How do you make sure that an MR is not merged before its parent MR? We don't have that dependend-MR paid Gitlab feature, unfortunately.

So when you do `git review -m` to merge the MRs, it will enforce the dependency chain. A commit's MR isn't mergeable until all the commits before it become mergeable.

**Comment by clonejo** [comment]
I guess that would make sense if we had an approval gate, but in our team the reviewer typically just merges on their own.

edit: but i guess can build sth into gerritlab using approvals as well, even if we don't have that configured as a gate in gitlab. i don't want to force any changes in process on the team while i'm just experimenting.

**Comment by clonejo** [comment]
When you merge i would put up the next PR. (or you just pull from https://github.com/clonejo/gerritlab/commits/main)

**Comment by yaoyuannnn** [comment]
> I guess that would make sense if we had an approval gate, but in our team the reviewer typically just merges on their own.
> 
> edit: but i guess can build sth into gerritlab using approvals as well, even if we don't have that configured as a gate in gitlab. i don't want to force any changes in process on the team while i'm just experimenting.

Yes, something can be created to block the later commits to be merged if there are outstanding older commits.

**Pull request merged**
