### PR TITLE
Rename submit of an MR to merge

### PR DESCRIPTION
**Pull request by clonejo**
"Submit" was confusing to me, and does not seem to be nomenclature used
by Gitlab itself. Initially i assumed "submit" meant creating an MR.

Change-Id: Ia85b07c27ee0082e39ffce531dfa8b57eb85c073

### CODE REVIEW

**Comment by clonejo** [comment]
This is the last one for now :)

**Comment by yaoyuannnn** [comment]
Looks good :)

**Comment by clonejo** [comment]
Ahhh, turns out "submit" is Gerrit nomenclature: https://gerrit-review.googlesource.com/Documentation/intro-user.html#submit

**Comment by yaoyuannnn** [comment]
I always leave the author to merge the MR/PR after approval. So feel free to merge for future changes ;)

**Comment by yaoyuannnn** [comment]
> Ahhh, turns out "submit" is Gerrit nomenclature: https://gerrit-review.googlesource.com/Documentation/intro-user.html#submit

I think "merge" does make more sense since the user is using GItLab anyway.

**Comment by yaoyuannnn** [comment]
Looks like CircleCI is not trigged for PRs. Let me enable that.

**Pull request merged**
